### ISSUE TITLE
Demo with new version

### ISSUE THREAD

**Issue by yaroslavkasatikov** [isovalent/cilium-grafana-observability-demo#11]
Hey team,
Would it be possible to update demo and show it with latest version (1.14.x)?
As I understood it will require Envoy etc
What will be changed?

**Comment by chancez** [comment]
We've turned this demo into an [Instruct Lab](https://isovalent.com/labs/hubble-grafana-golden-signals/) which gets regular updates. To try it with the latest versions of Cilium, visit the lab.
