### ISSUE TITLE
Inaccurate README instruction with Installing Prometheus-Operator CRDs 

### ISSUE THREAD

**Issue by livingshade** [isovalent/cilium-grafana-observability-demo#7]
I attempted to run a demo by following the instructions in the README file. According to the instructions, I needed to install Prometheus-operator CRDs before installing Cilium:

> And we're going to install the Prometheus-operator CRDs before cilium, to avoid issues installing the Cilium ServiceMonitor:
> 
> ```bash
> helm template kube-prometheus prometheus-community/kube-prometheus-stack --include-crds \
>   | yq 'select(.kind == "CustomResourceDefinition") * {"metadata": {"annotations": {"meta.helm.sh/release-name": "kube-prometheus", "meta.helm.sh/release-namespace": "monitoring"}}}' \
>   | kubectl create -f -
> ```

When executing the scripts above, it told me `no objects to create`. I found out that `yq select...` actually returned nothing. 

I had to skip that and ran the following script:

> ```
> helm upgrade cilium cilium/cilium \
>   --version 1.13.0-rc2 \
>   --install \
>   --wait \
>   --namespace kube-system \
>   --values helm/cilium-values.yaml \
>   --set kubeProxyReplacement=strict \
>   --set k8sServiceHost="${MASTER_IP}" \
>   --set k8sServicePort=6443
> ```

I got `Error: execution error at (cilium/templates/validate.yaml:21:9): Service Monitor requires monitoring.coreos.com/v1 CRDs. Please refer to https://github.com/prometheus-operator/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml` 

I tried to apply the yaml file mentioned in the error message and ran the 'helm upgrade cilium' command again, and this time it worked. After that, I was able to successfully run the demo.

I don't know whether this is the right thing to do, but it worked anyway. I guess that the software has been upgraded, and the README file should be updated to avoid this misunderstanding in the future.

**Comment by kaworu** [comment]
@livingshade are you using https://github.com/kislyuk/yq or https://github.com/mikefarah/yq? For me it is working with the former.

**Comment by livingshade** [comment]
> @livingshade are you using https://github.com/kislyuk/yq or https://github.com/mikefarah/yq? For me it is working with the former.

I am using one that link in README leads me to: https://github.com/mikefarah/yq/

**Comment by kaworu** [comment]
@livingshade I see! @chancez care to take a look? I think we need to update the README accordingly :pray:

**Comment by chancez** [comment]
This should work with https://github.com/mikefarah/yq/, I just tested it locally:
```
$ helm template kube-prometheus prometheus-community/kube-prometheus-stack --include-crds \
  | yq 'select(.kind == "CustomResourceDefinition") * {"metadata": {"annotations": {"meta.helm.sh/release-name": "kube-prometheus", "meta.helm.sh/release-namespace": "monitoring"}}}' \
  | kubectl create -f - --dry-run
W0327 09:00:52.624741   28107 helpers.go:636] --dry-run is deprecated and can be replaced with --dry-run=client.
customresourcedefinition.apiextensions.k8s.io/alertmanagerconfigs.monitoring.coreos.com created (dry run)
customresourcedefinition.apiextensions.k8s.io/alertmanagers.monitoring.coreos.com created (dry run)
customresourcedefinition.apiextensions.k8s.io/podmonitors.monitoring.coreos.com created (dry run)
customresourcedefinition.apiextensions.k8s.io/probes.monitoring.coreos.com created (dry run)
customresourcedefinition.apiextensions.k8s.io/prometheuses.monitoring.coreos.com created (dry run)
customresourcedefinition.apiextensions.k8s.io/prometheusrules.monitoring.coreos.com created (dry run)
customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com created (dry run)
customresourcedefinition.apiextensions.k8s.io/thanosrulers.monitoring.coreos.com created (dry run)
```

Can you provide the output of the following commands?

```
helm --version
helm search repo  kube-prometheus-stack 
yq --version
```

**Comment by livingshade** [comment]
Sorry, it seems that I have yq not properly installed, and it works for me after I reinstalled the lastest version. Sorry for the inconvenience, I will close the issue.
